title = "臨床血液學白血球圖譜"

[answer]
1 = "Segments"
2 = "Segments"
3 = "Segments"
4 = "Segments"
5 = "Segments"
6 = "Segments"
7 = "Segments"
8 = "Segments"
9 = "Segments"
10 = "Segments"
11 = "Segments"
12 = "Segments"
13 = "Segments"
14 = "Segments"
15 = "Segments"
16 = "Segments"
17 = "Segments"
18 = "Segments"
19 = "Segments"
20 = "Segments"
21 = "Segments"
22 = "Segments"
23 = "Segments"
24 = "Segments"
25 = "Segments"
26 = "Segments"
27 = "Segments"
28 = "Segments"
29 = "Segments"
30 = "Segments"
31 = "Segments"
32 = "Segments"
33 = "Segments"
34 = "Segments"
35 = "Segments"
36 =  "Eosinophils"
37 =  "Eosinophils"
38 =  "Eosinophils"
39 =  "Eosinophils"
40 =  "Eosinophils"
41 =  "Eosinophils"
42 =  "Eosinophils"
43 =  "Eosinophils"
44 =  "Eosinophils"
45 =  "Eosinophils"
46 =  "Eosinophils"
47 =  "Eosinophils"
48 =  "Eosinophils"
49 =  "Eosinophils"
50 =  "Eosinophils"
51 =  "Eosinophils"
52 =  "Eosinophils"
53 =  "Eosinophils"
54 =  "Eosinophils"
55 =  "Eosinophils"
56 =  "Eosinophils"
57 =  "Eosinophils"
58 =  "Eosinophils"
59 =  "Eosinophils"
60 =  "Eosinophils"
61 =  "Eosinophils"
62 =  "Eosinophils"
63 =  "Eosinophils"
64 =  "Eosinophils"
65 =  "Eosinophils"
66 =  "Eosinophils"
67 =  "Eosinophils"
68 =  "Eosinophils"
69 =  "Eosinophils"
70 =  "Eosinophils"
71 =  "Eosinophils"
72 =  "Eosinophils"
73 =  "Eosinophils"
74 =  "Eosinophils"
75 =  "Eosinophils"
76 =  "Basophils"
77 = "Basophils"
78 = "Basophils"
79 =  "Basophils"
80 =  "Basophils"
81 = "Basophils"
82 = "Basophils"
83 = "Basophils"
84 = "Basophils"
85 = "Basophils"
86 = "Basophils"
87 = "Basophils"
88 = "Basophils"
89 = "Basophils"
90 = "Basophils"
91 = "Basophils"
92 = "Basophils"
93 = "Basophils"
94 = "Basophils"
95 = "Basophils"
96 = "Basophils"
97 = "Basophils"
98 = "Basophils"
99 = "Basophils"
100 = "Basophils"
101 = "Basophils"
102 = "Basophils"
103 = "Basophils"
104 = "Basophils"
105 = "Basophils"
106 = "Basophils"
107 = "Basophils"
108 = "Basophils"
109 = "Basophils"
110 = "Basophils"
111 = "Basophils"
112 = "Basophils"
113 = "Basophils"
114 = "Basophils"
115 = "Basophils"
116 = "Basophils"
117 = "Basophils"
118 = "Lymphocytes"
119 = "Lymphocytes"
120 = "Lymphocytes"
121 = "Lymphocytes"
122 = "Lymphocytes"
123 = "Lymphocytes"
124 = "Lymphocytes"
125 = "Lymphocytes"
126 = "Lymphocytes"
127 = "Lymphocytes"
128 = "Lymphocytes"
129 = "Lymphocytes"
130 = "Lymphocytes"
131 = "Lymphocytes"
132 = "Lymphocytes"
133 = "Lymphocytes"
134 = "Lymphocytes"
135 = "Lymphocytes"
136 = "Lymphocytes"
137 = "Lymphocytes"
138 = "Lymphocytes"
139 = "Lymphocytes"
140 = "Lymphocytes"
141 = "Lymphocytes"
142 = "Lymphocytes"
143 = "Lymphocytes"
144 = "Lymphocytes"
145 = "Lymphocytes"
146 = "Lymphocytes"
147 = "Lymphocytes"
148 = "Lymphocytes"
149 = "Lymphocytes"
150 = "Lymphocytes"
151 = "Lymphocytes"
152 = "Lymphocytes"
153 = "Lymphocytes"
154 = "Lymphocytes"
155 = "Lymphocytes"
156 = "Lymphocytes"
157 = "Lymphocytes"
158 = "Lymphocytes"
159 = "Lymphocytes"
160 = "Lymphocytes"
161 = "Lymphocytes"
162 = "Lymphocytes"
163 = "Lymphocytes"
164 = "Lymphocytes"
165 = "Lymphocytes"
166 = "Lymphocytes"
167 = "Lymphocytes"
168 = "Lymphocytes"
169 = "Lymphocytes"
170 = "Lymphocytes"
171 = "Lymphocytes"
172 = "Lymphocytes"
173 = "Lymphocytes"
174 = "Lymphocytes"
175 = "Lymphocytes"
176 = "Lymphocytes"
177 = "Monocytes"
178 = "Monocytes"
179 = "Monocytes"
180 = "Monocytes"
181 = "Monocytes"
182 = "Monocytes"
183 = "Monocytes"
184 = "Monocytes"
185 = "Monocytes"
186 = "Monocytes"
187 = "Monocytes"
188 = "Monocytes"
189 = "Monocytes"
190 = "Monocytes"
191 = "Monocytes"
192 = "Monocytes"
193 = "Monocytes"
194 = "Monocytes"
195 = "Monocytes"
196 = "Monocytes"
197 = "Monocytes"
198 = "Monocytes"
199 = "Monocytes"
200 = "Monocytes"
201 = "Monocytes"
202 = "Monocytes"
203 = "Monocytes"
204 = "Monocytes"
205 = "Monocytes"
206 = "Monocytes"
207 = "Monocytes"
208 = "Monocytes"
209 = "Monocytes"
210 = "Monocytes"
211 = "Monocytes"
212 = "Monocytes"
213 = "Monocytes"
214 = "Monocytes"
215 = "Monocytes"
216 = "Monocytes"
217 = "Monocytes"
218 = "Monocytes"
219 = "Monocytes"
220 = "Monocytes"
221 = "Monocytes"
222 = "Monocytes"
223 = "Monocytes"
224 = "Monocytes"
225 = "Neutrophils-Band"
226 = "Neutrophils-Band"
227 = "Neutrophils-Band"
228 = "Neutrophils-Band"
229 = "Neutrophils-Band"
230 = "Neutrophils-Band"
231 = "Neutrophils-Band"
232 = "Neutrophils-Band"
233 = "Neutrophils-Band"
234 = "Neutrophils-Band"
235 = "Neutrophils-Band"
236 = "Neutrophils-Band"
237 = "Neutrophils-Band"
238 = "Neutrophils-Band"
239 = "Neutrophils-Band"
240 = "Neutrophils-Band"
241 = "Neutrophils-Band"
242 = "Neutrophils-Band"
243 = "Neutrophils-Band"
244 = "Neutrophils-Band"
245 = "Neutrophils-Band"
246 = "Neutrophils-Band"
247 = "Neutrophils-Band"
248 = "Neutrophils-Band"
249 = "Neutrophils-Band"
250 = "Neutrophils-Band"
251 = "Neutrophils-Band"
252 = "Neutrophils-Band"
253 = "Neutrophils-Band"
254 = "Neutrophils-Band"
255 = "Neutrophils-Band"
256 = "Neutrophils-Band"
257 = "Neutrophils-Band"
258 = "Neutrophils-Band"
259 = "Neutrophils-Band"
260 = "Neutrophils-Band"
261 = "Neutrophils-Band"
262 = "Neutrophils-Band"
263 = "Neutrophils-Band"
264 = "Neutrophils-Band"
265 = "Neutrophils-Band"
266 = "Neutrophils-Band"
267 = "Neutrophils-Band"
268 = "Neutrophils-Band"
269 = "Neutrophils-Band"
270 = "Neutrophils-Band"
271 = "Neutrophils-Band"
272 = "Neutrophils-Band"
273 = "Neutrophils-Band"
274 = "Neutrophils-Band"
275 = "Neutrophils-Band"
276 = "Neutrophils-Band"
277 = "Atypical lymphocytes"
278 = "Atypical lymphocytes"
279 = "Atypical lymphocytes"
280 = "Atypical lymphocytes"
281 = "Atypical lymphocytes"
282 = "Atypical lymphocytes"
283 = "Atypical lymphocytes"
284 = "Atypical lymphocytes"
285 = "Atypical lymphocytes"
286 = "Atypical lymphocytes"
287 = "Atypical lymphocytes"
288 = "Atypical lymphocytes"
289 = "Atypical lymphocytes"
290 = "Atypical lymphocytes"
291 = "Atypical lymphocytes"
292 = "Atypical lymphocytes"
293 = "Atypical lymphocytes"
294 = "Atypical lymphocytes"
295 = "Atypical lymphocytes"
296 = "Atypical lymphocytes"
297 = "Large granule lymphocytes"
298 = "Large granule lymphocytes"
299 = "Large granule lymphocytes"
300 = "Large granule lymphocytes"
301 = "Large granule lymphocytes"
302 = "Large granule lymphocytes"
303 = "Large granule lymphocytes"
304 = "Large granule lymphocytes"
305 = "Large granule lymphocytes"
306 = "Large granule lymphocytes"
307 = "Large granule lymphocytes"
308 = "Large granule lymphocytes"
309 = "Large granule lymphocytes"
310 = "Large granule lymphocytes"
311 = "Large granule lymphocytes"
312 = "Large granule lymphocytes"
313 = "Large granule lymphocytes"
314 = "Large granule lymphocytes"
315 = "Large granule lymphocytes"
316 = "Large granule lymphocytes"
317 = "Large granule lymphocytes"
318 = "Large granule lymphocytes"
319 = "Large granule lymphocytes"
320 = "Large granule lymphocytes"
321 = "Large granule lymphocytes"
322 = "Large granule lymphocytes"
323 = "Large granule lymphocytes"
324 = "Large granule lymphocytes"
325 = "Large granule lymphocytes"
326 = "Large granule lymphocytes"
327 = "Large granule lymphocytes"
328 = "Large granule lymphocytes"
329 = "Large granule lymphocytes"
330 = "Large granule lymphocytes"
331 = "Large granule lymphocytes"
332 = "Large granule lymphocytes"
333 = "Large granule lymphocytes"
334 = "Large granule lymphocytes"
335 = "Large granule lymphocytes"
336 = "Large granule lymphocytes"
337 = "Large granule lymphocytes"
338 = "Large granule lymphocytes"
339 = "Large granule lymphocytes"
340 = "Large granule lymphocytes"
341 = "Large granule lymphocytes"
342 = "Large granule lymphocytes"
343 = "Large granule lymphocytes"
344 = "Large granule lymphocytes"
345 = "Large granule lymphocytes"
346 = "Large granule lymphocytes"
347 = "Large granule lymphocytes"
348 = "Large granule lymphocytes"
349 = "Large granule lymphocytes"
350 = "Large granule lymphocytes"
351 = "Large granule lymphocytes"
352 = "Large granule lymphocytes"
353 = "Large granule lymphocytes"
354 = "Large granule lymphocytes"
355 = "Large granule lymphocytes"
356 = "Large granule lymphocytes"
357 = "Large granule lymphocytes"
358 = "Large granule lymphocytes"
359 = "Immature basophils"
360 = "Immature basophils"
361 = "Immature basophils"
362 = "Immature basophils"
363 = "Immature basophils"
364 = "Immature basophils"
365 = "Immature basophils"
366 = "Immature basophils"
367 = "Immature basophils"
368 = "Immature basophils"
369 = "Immature basophils"
370 = "Immature basophils"
371 = "Immature basophils"
372 = "Immature basophils"
373 = "Immature basophils"
374 = "Immature basophils"
375 = "Immature basophils"
376 = "Immature eosinophils"
377 = "Immature eosinophils"
378 = "Immature eosinophils"
379 = "Immature eosinophils"
380 = "Immature eosinophils"
381 = "Immature eosinophils"
382 = "Immature eosinophils"
383 = "Immature eosinophils"
384 = "Immature eosinophils"
385 = "Immature eosinophils"
386 = "Immature eosinophils"
387 = "Immature eosinophils"
388 = "Immature eosinophils"
389 = "Immature eosinophils"
390 = "Immature eosinophils"
391 = "Immature eosinophils"
392 = "Immature eosinophils"
393 = "Immature eosinophils"
394 = "Immature eosinophils"
395 = "Immature eosinophils"
396 = "Immature eosinophils"
397 = "Immature eosinophils"
398 = "Immature eosinophils"
399 = "Immature eosinophils"
400 = "Immature eosinophils"
401 = "Immature eosinophils"
402 = "Immature eosinophils"
403 = "Immature eosinophils"
404 = "Immature eosinophils"
405 = "Immature eosinophils"
406 = "Immature eosinophils"
407 = "Giant platelets(P-LCR)"
408 = "Giant platelets(P-LCR)"
409 = "Giant platelets(P-LCR)"
410 = "Giant platelets(P-LCR)"
411 = "Giant platelets(P-LCR)"
412 = "Giant platelets(P-LCR)"
413 = "Giant platelets(P-LCR)"
414 = "Giant platelets(P-LCR)"
415 = "Giant platelets(P-LCR)"
416 = "Giant platelets(P-LCR)"
417 = "Giant platelets(P-LCR)"
418 = "Giant platelets(P-LCR)"
419 = "Giant platelets(P-LCR)"
420 = "Giant platelets(P-LCR)"
421 = "Giant platelets(P-LCR)"
422 = "Giant platelets(P-LCR)"
423 = "Giant platelets(P-LCR)"
424 = "Giant platelets(P-LCR)"
425 = "Giant platelets(P-LCR)"
426 = "Giant platelets(P-LCR)"
427 = "Giant platelets(P-LCR)"
428 = "Giant platelets(P-LCR)"
429 = "Giant platelets(P-LCR)"
430 = "Giant platelets(P-LCR)"
431 = "Giant platelets(P-LCR)"
432 = "Giant platelets(P-LCR)"
433 = "Giant platelets(P-LCR)"
434 = "Giant platelets(P-LCR)"
435 = "Giant platelets(P-LCR)"
436 = "Giant platelets(P-LCR)"
437 = "Giant platelets(P-LCR)"
438 = "Giant platelets(P-LCR)"
439 = "Giant platelets(P-LCR)"
440 = "Giant platelets(P-LCR)"
441 = "Giant platelets(P-LCR)"
442 = "Giant platelets(P-LCR)"
443 = "Giant platelets(P-LCR)"
444 = "Giant platelets(P-LCR)"
445 = "Giant platelets(P-LCR)"
446 = "Giant platelets(P-LCR)"
447 = "Giant platelets(P-LCR)"