title = "寄生蟲期末跑台練習"

[answer]
1 = "Lymnaea spp.凌螺 / 牛羊肝吸蟲"
2 = "Parafossarulus spp.派螺 / 中華肝吸蟲"
3 = "Hippeutis spp.黑螺 / 薑片蟲"
4 = "Segmentina spp.小扁卷螺 / 薑片蟲"
5 = "Biomphalaria spp. 大扁卷螺 / 曼森住血吸蟲"
6 = "Oncomelania Formosana 釘螺 / 日本住血吸蟲"
7 = "Thiara spp. 顆粒洗螺 / 中華肝吸蟲"