title = "臨床微生物實驗-期中"

[answer]
1 = "Bacillus subtilis"
2 = "E. coli on BAP"
3 = "Bacillus subtilis"
4 = "Staphylococcus epidermidis"
5 = "Nesseris spp. (EM)"
6 = "E. coli"
7 = "Streptococcus pneumoniae"
8 = "Nesseris spp."
9 = "Diphtheroids"
10 = "Diphtheroids"
11 = "Staphylococcus spp"
12 = "Streptococcus aureus"
13 = "Micrococcus spp. (on BAP)"
14 = "Micrococcus spp."
15 = "Nesseris spp. Yellow pigment"
16 = "Hemolysis"
17 = "Gamma-Streptococcus"
18 = "Streptococcus pneumoniae"
19 = "Streptococcus aureus"
20 = "Streptococcus pneumoniae"
21 = "Bacillus subtilis"
22 = "Psudomonas aeruginosa"
23 = "Psudomonas aeruginosa"
24 = "Psudomonas aeruginosa"
25 = "Spore stain"
26 = "Staphylococcus aureus"
27 = "Staphylococcus spp 0.8-1.0 um"
28 = "Bacillus subtilis"
29 = "Bacillus subtilis"
30 = "Bacillus subtilis"
31 = "E. coli"
32 = "E. coli"
33 = "Streptococcus pyogene"
34 = "Streptococcus pyogene"
35 = "Streptococcus agalatiae"
36 = "Streptococcus pyogene-gamma hemolysis"
37 = "上GBS 下GAS"
38 = "group C G Streptococci "
39 = "PYR test"
40 = "Streptococcus pyogene"
41 = "group C F G Streptococci"
42 = "scalet fever"
43 = "Streptococcus pyogene"
44 = "scalet fever"
45 = "Streptococcus pyogene"
46 = "Bacitracin susceptibility test-Streptococcus pyogene"
47 = "stabbed medium-beta hemolysis"
48 = "enterococcus"
49 = "tube coagulase test"
50 = "OF test(+)-staphylococci"
51 = "staphylococcs aureus"
52 = "micrococci"
53 = "api test*"
54 = "oxacillin screen plate"
55 = "舌粲紙蓮花"
56 = "staphylococci"
57 = "toxic shock syndrome"
58 = "S.epidermidis"
59 = "Micrococcus"
60 = "MSA test 左 S.aureus 右S.epidermidis"
61 = "Mcrococcus"
62 = "catalase test(+)"
63 = "slide coagulase test"
64 = "DNase tube test 左 S.aureus 右S.epidermidis"
65 = "DNase plate test 左 S.aureus 右S.epidermidis"
66 = "Latex agglutination test 左 S.aureus 右CNS"
67 = "FUrazolidone susceptibility test"
68 = "Bacitracin susceptibility test 左staphylococci 右Micrococci"
69 = "Novobiocin susceptibility test 左S.saprophyticus 右S.epidermidis"
70 = "S.saprophyticus"
71 = "A:Enterococcus faecium B:Enterococcus faecalis"
72 = "methyl-alpha-D-glucopyranoside"
73 = "motility test"
74 = "E. casseliflavus"
75 = "streptococcus pneumoniae"
76 = "streptococcus pneumoniae"
77 = "streptococcus pneumoniae"
78 = "streptococcus pneumoniae"
79 = "quellung test-streptococcus pneumoniae"
80 = "viridan streptococcus"
81 = "E.faecalis"
82 = "Optochin-Viridian Streptococci"
83 = "API20E"
84 = "Enterococcus"
85 = "Enterococcus"
86 = "Enterococcus"
87 = "E.faecalis&E.faecium"
88 = "API20E"
89 = " Arabinose"
90 = "EMB agar"
91 = "Orn(-),Arg(+),Lys(-)"
92 = "cytochrom oxidase test"
93 = "cytochrom oxidase test(+)"
94 = "70622-E.coli"
95 = "生化八管"
96 = "E.coli on EMB"
97 = "lactose(-)"
98 = "MacConkey agar"
99 = "MacConkey agar"
100 = "E.coli"
101 = "citrate + -"
102 = "urea - + strong+"
103 = "SIM: + - -"
104 = "VP:- +"
105 = "TSI:"
106 = "SIM:motility + -"
107 = "IPA(+)"
108 = "API20"
109 = "API20E"
110 = "india ink-Cryptococcus"
111 = "india ink-Cryptococcus"
112 = "IMViC of Klebsiella, Enterobacter, & Serratia"
113 = "73042"
114 = "A Klebsiella pneumoniae producing an ESBL"
115 = "A Klebsiella pneumoniae producing an ESBL"
116 = "下EMB 上BAP-Klebsiella pneumoniae"
117 = "EMB-Klebsiella pneumoniae"
118 = "BAP-Klebsiella pneumoniae"
119 = "string test"
120 = "india ink-Klebsiella pneumoniae"