title = "寄生蟲期末跑台練習"

[answer]
1 = "47. Metagonimus yodogawai 子宮在中段"
2 = "39. eggs of Paragonimus westermani"
3 = "Metacercia 任意一種雌雄同體吸蟲"
4 = "35. egg of Clonorchis sinensis"
5 = "43. eggs of Fasciolopsis buski"
6 = "eggs of Schistosoma japonicum"
7 = "Cross section of Fasciolopsis buski(Anterior)"
8 = "Thiaragraniferu 顆粒洗螺 / 中華肝吸蟲"
9 = "eggs of schistosoma mansoni fibrous tissue"
10 = "Echinostoma revolutum"
11 = "Schistosoma mansoni cross sec."
12 = "eggs of Fasciolopsis buski"
13 = "Schistosoma japonicum cross sec. in intestine"
14 = "Schistosoma japonicum female"
15 = "egg of Paragonmus westermani"
16 = "Balantidium coli trophozoite form"
17 = "cercaria of clonorchis sinensis"
18 = "Schistosoma mansoni female"
19 = "Opisthorchis viverrini"
20 = "eggs of Schistosoma haematobium"
21 = "eggs of Schistosoma haematobium"
22 = "Redia of Echinostoma"
23 = "Balantidium coli cyst form"
24 = "Schistosoma japonicum male; 6-8 testis"
25 = "Schistosoma japonicum in intestine"
26 = "Dicrocoelium dentriticum"
27 = "bubble....."
28 = "egg of Clonorchis sinensis"
29 = "eggs of Paragonimus westermani"
30 = "OncomelaniaFormosana 釘螺 / 日本住血吸蟲"
31 = "Schistosoma mansoni cercaria"
32 = "Schistosoma japonicum male+female"
33 = "Plasmodium vivax(thin smear)"
34 = "Plasmodium vivax(thick smear)"
35 = "Biomphalariaglabrata 大扁卷螺 / 曼森住血吸蟲"
36 = "Plasmodium falciparum gametocyte"
37 = "Plasmodium falciparum gametocyte"
38 = "Plasmodium malariae"
39 = "isospora spp."
40 = "Toxoplasma gondii"
41 = "Toxoplasma gondii pseudocyst form in brain"
42 = "Pneumocystis carinii sec. rat lung"
43 = "Toxoplasma gondii"
44 = "Segmentinahemisulcospira 小扁卷螺 / 薑片蟲"
45 = "Hippeutis spp.黑螺 / 薑片蟲"
46 = "Balantidium coli sec. intestine"
47 = "Entamoeba histolytica cyst form"
48 = "Entamoeba histolytica trophozoite form"
49 = "Entamoeba histolytica 錐形瓶潰瘍"
50 = "Entamoeba coli cyst form"
51 = "Trypanosoma cruzi epimastigote"
52 = "Trypanosoma cruzi amastigote in rat heart. cross sec."
53 = "D39 cerebral malaria?"
54 = "Leishmania tropica promatigote"
55 = "Trypanosoma rhodesiense trypomastigote in rat blood"
56 = "Trypanosoma gambiense trypomastigote in rat blood"
57 = "Unknown"
58 = "Trypanosoma cruzi epimastigote"
59 = "Trypanosoma cruzi amastigote"
60 = "Giardia lambia trophozoite"
61 = "Giardia lambia cyst"
62 = "94. Trichomonas vagigalis"
63 = "D39 cerebral malaria"
64 = "Entamoeba histolytica trophozoite form (MIF stain)"
65 = "65 Entamoeba histolytica cyst form. (fresh stool)"
66 = "Entamoeba histolytica cyst form. (MIF stain)"
67 = "Giardia lamblia cyst form"
68 = "Plasmodium falciparum gametocyte"
69 = "Lymnaea spp.凌螺 / 牛羊肝吸蟲"
70 = "Parafossarulus spp.派螺 / 中華肝吸蟲"